language: go

go_import_path: github.com/ioncloud64/freemegb

go:
  - 1.13

addons:
  apt:
    packages:
      - gtk+3.0
      - libgtk-3-dev
      - libcairo2-dev
      - libglib2.0-dev
      - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo /usr/bin/Xvfb $DISPLAY 2>1 > /dev/null &
  - "export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)"
  - "export Glib_VERSION=$(pkg-config --modversion glib-2.0)"
  - "export Cairo_VERSION=$(pkg-config --modversion cairo)"
  - "export Pango_VERSION=$(pkg-config --modversion pango)"

install:
  - go get github.com/esiqveland/notify
  - go get -u -v -tags gtk_$GTK_VERSION github.com/gotk3/gotk3/gtk
  - make
