language: go

go_import_path: github.com/ioncloud64/freemegb

go:
  - 1.13

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libcairo2-dev
      - libglib2.0-dev
      - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo /usr/bin/Xvfb $DISPLAY 2>1 > /dev/null

install:
  - make
